import type { CheckedAirport, FlightRecord } from "./type";

/** 当前个人档案中的机场打卡数据，后续可迁移到后端接口。 */
export const CHECKED_AIRPORTS: CheckedAirport[] = [
    {
        name: "北京大兴国际机场",
        lat: 39.509945,
        lng: 116.41092,
        type: "airport",
        description: "中国北京市北京大兴国际机场",
    },
    {
        name: "北京首都国际机场",
        lat: 40.079856,
        lng: 116.603112,
        type: "airport",
        description: "中国北京市北京首都国际机场",
    },
    {
        name: "上海虹桥国际机场",
        lat: 31.197875,
        lng: 121.336319,
        type: "airport",
        description: "中国上海市上海虹桥国际机场",
    },
    {
        name: "上海浦东国际机场",
        lat: 31.144344,
        lng: 121.808273,
        type: "airport",
        description: "中国上海市上海浦东国际机场",
    },
    {
        name: "天津滨海国际机场",
        lat: 39.124474,
        lng: 117.346107,
        type: "airport",
        description: "中国天津市天津滨海国际机场",
    },
    {
        name: "西安咸阳国际机场",
        lat: 34.447119,
        lng: 108.751592,
        type: "airport",
        description: "中国陕西省西安咸阳国际机场",
    },
    {
        name: "宜昌三峡国际机场",
        lat: 30.55655,
        lng: 111.479988,
        type: "airport",
        description: "中国湖北省宜昌三峡国际机场",
    },
    {
        name: "杭州萧山国际机场",
        lat: 30.229503,
        lng: 120.434453,
        type: "airport",
        description: "中国浙江省杭州萧山国际机场",
    },
    {
        name: "东京成田国际机场",
        lat: 35.771986,
        lng: 140.39285,
        type: "airport",
        description: "日本千叶县东京成田国际机场",
    },
    {
        name: "大阪关西国际机场",
        lat: 34.435446,
        lng: 135.244167,
        type: "airport",
        description: "日本大阪关西国际机场",
    },
    {
        name: "名古屋中部国际机场",
        lat: 34.858414,
        lng: 136.805408,
        type: "airport",
        description: "日本名古屋中部国际机场",
    },
    {
        name: "曼谷素万那普国际机场",
        lat: 13.690017,
        lng: 100.750112,
        type: "airport",
        description: "泰国曼谷素万那普国际机场",
    },
    {
        name: "曼谷廊曼国际机场",
        lat: 13.912583,
        lng: 100.607036,
        type: "airport",
        description: "泰国曼谷廊曼国际机场",
    },
    {
        name: "普吉国际机场",
        lat: 8.1132,
        lng: 98.316872,
        type: "airport",
        description: "泰国普吉国际机场",
    },
    {
        name: "巴塞罗那埃尔普拉特机场",
        lat: 41.297445,
        lng: 2.083294,
        type: "airport",
        description: "西班牙巴塞罗那埃尔普拉特机场",
    },
    {
        name: "罗马菲乌米奇诺机场",
        lat: 41.800278,
        lng: 12.238889,
        type: "airport",
        description: "意大利罗马菲乌米奇诺机场",
    },
    {
        name: "巴黎奥利机场",
        lat: 48.726243,
        lng: 2.365247,
        type: "airport",
        description: "法国巴黎奥利机场",
    },
    {
        name: "三亚凤凰国际机场",
        lat: 18.302897,
        lng: 109.412272,
        type: "airport",
        description: "中国海南省三亚凤凰国际机场",
    },
    {
        name: "卡萨布兰卡穆罕默德五世机场",
        lat: 33.367467,
        lng: -7.58997,
        type: "airport",
        description: "摩洛哥卡萨布兰卡穆罕默德五世国际机场",
    },
    {
        name: "首尔仁川国际机场",
        lat: 37.460191,
        lng: 126.440696,
        type: "airport",
        description: "韩国首尔仁川国际机场",
    },
    {
        name: "首尔金浦国际机场",
        lat: 37.558311,
        lng: 126.790586,
        type: "airport",
        description: "韩国首尔金浦国际机场",
    },
    {
        name: "庆阳机场",
        lat: 35.799702,
        lng: 107.602546,
        type: "airport",
        description: "中国甘肃省庆阳机场",
    },
    {
        name: "昆明长水国际机场",
        lat: 25.101944,
        lng: 102.929167,
        type: "airport",
        description: "中国云南省昆明市昆明长水国际机场",
    },
    {
        name: "武汉天河国际机场",
        lat: 30.7838,
        lng: 114.2081,
        type: "airport",
        description: "中国湖北省武汉市武汉天河国际机场",
    },
    {
        name: "重庆江北国际机场",
        lat: 29.7192,
        lng: 106.641,
        type: "airport",
        description: "中国重庆市重庆江北国际机场",
    },
    {
        name: "广州白云国际机场",
        lat: 23.392436,
        lng: 113.298786,
        type: "airport",
        description: "中国广东省广州市广州白云国际机场",
    },
    {
        name: "东京羽田机场",
        lat: 35.549393,
        lng: 139.779839,
        type: "airport",
        description: "日本东京都东京国际机场（羽田机场）",
    },
    {
        name: "清迈国际机场",
        lat: 18.766847,
        lng: 98.962638,
        type: "airport",
        description: "泰国清迈府清迈国际机场",
    },
    {
        name: "新加坡樟宜机场",
        lat: 1.36442,
        lng: 103.991531,
        type: "airport",
        description: "新加坡樟宜机场",
    },
    {
        name: "悉尼机场",
        lat: -33.939922,
        lng: 151.175276,
        type: "airport",
        description: "澳大利亚悉尼机场（SYD）",
    },
    {
        name: "香港国际机场",
        lat: 22.308047,
        lng: 113.918481,
        type: "airport",
        description: "中国香港香港国际机场（HKG）",
    },
];

/** 当前个人档案中的乘机记录，按出发日期从新到旧排列。 */
export const FLIGHT_RECORDS: FlightRecord[] = [
    {
        airline: "国泰航空",
        aircraft: "350-900",
        origin: "北京首都",
        destination: "香港",
        routeKind: "one-way",
        departureDate: "2027-1-1",
    },
    {
        airline: "国泰航空",
        aircraft: "330-300",
        origin: "香港",
        destination: "北京首都",
        routeKind: "one-way",
        departureDate: "2027-1-4",
    },
    {
        airline: "新加坡航空",
        aircraft: "787-10",
        origin: "新加坡",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2026-10-8",
    },
    {
        airline: "新加坡航空",
        aircraft: "380-800",
        origin: "悉尼",
        destination: "新加坡",
        routeKind: "one-way",
        departureDate: "2026-10-7",
    },
    {
        airline: "新加坡航空",
        aircraft: "380-800",
        origin: "新加坡",
        destination: "悉尼",
        routeKind: "one-way",
        departureDate: "2026-10-2",
    },
    {
        airline: "新加坡航空",
        aircraft: "777-300ER",
        origin: "北京",
        destination: "新加坡",
        routeKind: "one-way",
        departureDate: "2026-10-1",
    },
    {
        airline: "大韩航空",
        aircraft: "737-900ER",
        origin: "首尔",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2026-9-6",
    },
    {
        airline: "大韩航空",
        aircraft: "321NEO",
        origin: "北京",
        destination: "首尔",
        routeKind: "one-way",
        departureDate: "2026-9-4",
    },
    {
        airline: "中国东方航空",
        aircraft: "321NEO",
        origin: "西安",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2026-8-23",
    },
    {
        airline: "中国东方航空",
        aircraft: "320NEO",
        origin: "北京",
        destination: "西安",
        routeKind: "one-way",
        departureDate: "2026-8-21",
    },
    {
        airline: "全日空",
        aircraft: "777-300ER",
        origin: "东京",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2026-6-20",
    },
    {
        airline: "全日空",
        aircraft: "767-300",
        origin: "北京",
        destination: "东京",
        routeKind: "one-way",
        departureDate: "2026-6-17",
    },
    {
        airline: "泰国航空",
        aircraft: "350-900",
        origin: "曼谷",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2026-5-5",
    },
    {
        airline: "泰国航空",
        aircraft: "320-200",
        origin: "清迈",
        destination: "曼谷",
        routeKind: "one-way",
        departureDate: "2026-5-2",
    },
    {
        airline: "中国东方航空",
        aircraft: "737-800",
        origin: "昆明",
        destination: "清迈",
        routeKind: "one-way",
        departureDate: "2026-4-29",
    },
    {
        airline: "中国东方航空",
        aircraft: "321-200",
        origin: "北京",
        destination: "昆明",
        routeKind: "one-way",
        departureDate: "2026-4-29",
    },
    {
        airline: "中国南方航空",
        aircraft: "321-200",
        origin: "西安",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2026-3-30",
    },
    {
        airline: "中国东方航空",
        aircraft: "321-200",
        origin: "北京",
        destination: "西安",
        routeKind: "one-way",
        departureDate: "2026-3-27",
    },
    {
        airline: "中国南方航空",
        aircraft: "321-200",
        origin: "广州",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2026-2-20",
    },
    {
        airline: "中国南方航空",
        aircraft: "737-800",
        origin: "西安",
        destination: "广州",
        routeKind: "one-way",
        departureDate: "2026-2-18",
    },
    {
        airline: "河北航空",
        aircraft: "737-800",
        origin: "西安",
        destination: "西峰",
        routeKind: "one-way",
        departureDate: "2026-2-15",
    },
    {
        airline: "中国国际航空",
        aircraft: "330-300",
        origin: "首尔",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2026-1-4",
    },
    {
        airline: "中国国际航空",
        aircraft: "737-800",
        origin: "北京",
        destination: "首尔",
        routeKind: "one-way",
        departureDate: "2026-1-1",
    },
    {
        airline: "泛航航空",
        aircraft: "320-200",
        origin: "罗马",
        destination: "巴黎",
        routeKind: "one-way",
        departureDate: "2025-10-9",
    },
    {
        airline: "瑞安航空",
        aircraft: "737-MAX8",
        origin: "巴塞罗那",
        destination: "罗马",
        routeKind: "one-way",
        departureDate: "2025-10-6",
    },
    {
        airline: "中国东方航空",
        aircraft: "350-900",
        origin: "上海",
        destination: "巴塞罗那",
        routeKind: "one-way",
        departureDate: "2025-10-3",
    },
    {
        airline: "中国东方航空",
        aircraft: "321-200",
        origin: "北京",
        destination: "上海",
        routeKind: "one-way",
        departureDate: "2025-10-2",
    },
    {
        airline: "中国国际航空",
        aircraft: "737-800",
        origin: "名古屋",
        destination: "北京",
        routeKind: "round-trip",
        departureDate: "2025-8-29",
        returnDate: "8-31",
    },
    {
        airline: "泰国航空",
        aircraft: "350-900",
        origin: "曼谷",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2025-5-6",
    },
    {
        airline: "海南航空",
        aircraft: "737-MAX8",
        origin: "北京",
        destination: "曼谷",
        routeKind: "one-way",
        departureDate: "2025-5-2",
    },
    {
        airline: "海南航空",
        aircraft: "787-8",
        origin: "上海",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2025-5-1",
    },
    {
        airline: "中国东方航空",
        aircraft: "321-200",
        origin: "北京",
        destination: "上海",
        routeKind: "one-way",
        departureDate: "2025-5-1",
    },
    {
        airline: "吉祥航空",
        aircraft: "320-200",
        origin: "北京",
        destination: "大阪",
        routeKind: "round-trip",
        departureDate: "2025-3-20",
        returnDate: "3-24",
    },
    {
        airline: "中国国际航空",
        aircraft: "321-200",
        origin: "首尔",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2025-2-16",
    },
    {
        airline: "中国国际航空",
        aircraft: "737-800",
        origin: "北京",
        destination: "首尔",
        routeKind: "one-way",
        departureDate: "2025-2-14",
    },
    {
        airline: "中国东方航空",
        aircraft: "C919",
        origin: "西安",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2025-2-1",
    },
    {
        airline: "河北航空",
        aircraft: "737-800",
        origin: "北京",
        destination: "西峰",
        routeKind: "one-way",
        departureDate: "2025-1-28",
    },
    {
        airline: "泰国航空",
        aircraft: "350-900",
        origin: "曼谷",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2024-10-6",
    },
    {
        airline: "泰国航空",
        aircraft: "320",
        origin: "普吉岛",
        destination: "曼谷",
        routeKind: "one-way",
        routeSeparator: "arrow",
        departureDate: "2024-10-2",
    },
    {
        airline: "亚洲航空",
        aircraft: "320-200",
        origin: "曼谷",
        destination: "普吉岛",
        routeKind: "one-way",
        departureDate: "2024-9-28",
    },
    {
        airline: "亚洲航空",
        aircraft: "320-200",
        origin: "北京",
        destination: "曼谷",
        routeKind: "one-way",
        departureDate: "2024-9-28",
    },
    {
        airline: "中国东方航空",
        aircraft: "330-300",
        origin: "上海",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2024-5-5",
    },
    {
        airline: "中国国际航空",
        aircraft: "330-200",
        origin: "北京",
        destination: "上海",
        routeKind: "one-way",
        departureDate: "2024-5-2",
    },
    {
        airline: "春秋航空日本",
        aircraft: "737-800",
        origin: "东京",
        destination: "天津",
        routeKind: "one-way",
        departureDate: "2024-4-7",
    },
    {
        airline: "中国国际航空",
        aircraft: "330-300",
        origin: "北京",
        destination: "东京",
        routeKind: "one-way",
        departureDate: "2024-4-3",
    },
    {
        airline: "中国南方航空",
        aircraft: "321-200",
        origin: "西安",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2024-2-15",
    },
    {
        airline: "河北航空",
        aircraft: "737-800",
        origin: "北京",
        destination: "西峰",
        routeKind: "one-way",
        departureDate: "2024-2-8",
    },
    {
        airline: "中国联合航空",
        aircraft: "330-300",
        origin: "上海",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2024-1-1",
    },
    {
        airline: "中国国际航空",
        aircraft: "321-200",
        origin: "北京",
        destination: "上海",
        routeKind: "one-way",
        departureDate: "2023-12-29",
    },
    {
        airline: "天津航空",
        aircraft: "320-200",
        origin: "大阪",
        destination: "天津",
        routeKind: "one-way",
        departureDate: "2023-10-5",
    },
    {
        airline: "春秋航空日本",
        aircraft: "737-800",
        origin: "天津",
        destination: "东京",
        routeKind: "one-way",
        departureDate: "2023-9-28",
    },
    {
        airline: "首都航空",
        aircraft: "330-300",
        origin: "三亚",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2023-4-4",
    },
    {
        airline: "中国国际航空",
        aircraft: "320-200",
        origin: "北京",
        destination: "三亚",
        routeKind: "one-way",
        departureDate: "2023-4-1",
    },
    {
        airline: "中国南方航空",
        aircraft: "737-800",
        origin: "武汉",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2021-5-10",
    },
    {
        airline: "四川航空",
        aircraft: "320-200",
        origin: "昆明",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2021-2-26",
    },
    {
        airline: "中国东方航空",
        aircraft: "737-800",
        origin: "西安",
        destination: "昆明",
        routeKind: "one-way",
        departureDate: "2021-2-22",
    },
    {
        airline: "中国东方航空",
        aircraft: "321-200",
        origin: "北京",
        destination: "西安",
        routeKind: "one-way",
        departureDate: "2021-1-26",
    },
    {
        airline: "中国南方航空",
        aircraft: "321-200",
        origin: "武汉",
        destination: "北京",
        routeKind: "one-way",
        departureDate: "2020-12-8",
    },
    {
        airline: "中国南方航空",
        aircraft: "737-800",
        origin: "北京",
        destination: "武汉",
        routeKind: "one-way",
        departureDate: "2020-12-6",
    },
    {
        airline: "长龙航空",
        aircraft: "320-200",
        origin: "西安",
        destination: "杭州",
        routeKind: "one-way",
        departureDate: "2020-7-19",
    },
    {
        airline: "长安航空",
        aircraft: "737-800",
        origin: "西安",
        destination: "宜昌",
        routeKind: "one-way",
        departureDate: "2018-3-2",
    },
];
